name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: Luxcium
          email: 42672814+Luxcium@users.noreply.github.com

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Rush
        run: npm install -g @microsoft/rush

      - name: Verify package.json exists
        run: |
          if [ ! -f "services/rpc-worker-pool/package.json" ]; then
            echo "Error: package.json not found for @luxcium/rpc-worker-pool"
            exit 0
          fi

      - name: Verify no package.json in root directory
        run: |
          if [ -f "package.json" ]; then
            echo "Error: package.json found in the root directory"
            exit 1
          fi

      - name: Install dependencies
        run: rush update
        working-directory: ${{ github.workspace }}

      - name: Verify Change Logs
        run: rush change --verify
        working-directory: ${{ github.workspace }}

      - name: Rush rebuild
        run: rush rebuild --verbose --production
        working-directory: ${{ github.workspace }}

      - name: Add detailed logging
        run: |
          echo "Starting detailed logging..."
          # Add more detailed logging here as needed

      - name: Implement structured error handling
        run: |
          echo "Implementing structured error handling..."
          # Add try/catch blocks in custom scripts or actions as needed
