name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies with Rush
        run: rush update

      - name: Build projects
        run: rush build

      - name: Run tests
        run: rush test  # Assumes a Rush-friendly test command is defined
